### ISSUE TITLE
VLAN ID?

### ISSUE THREAD

**Issue by mobcdi** [peacey/udm-telus#2]
In your instructions is the vlan ID something I can choose or should I use the same VLAN ID as the broadband supplier?

**Comment by peacey** [comment]
Hi @mobcdi,

The LAN network VLAN ID (33) is not important, it can be anything you want.  The WAN VLAN ID depends on your provider. For Telus, there is no WAN VLAN ID.

**Comment by mobcdi** [comment]
Great thanks
