### ISSUE TITLE
Running igmpproxy in foreground error msg

### ISSUE THREAD

**Issue by Vandypants** [peacey/udm-telus#3]
Hey peacey

Love your work! You saved my bacon last year when I got Telus and discovered that their Wi-Fi sucks (personal opinion). After getting a UDM, and following your guide, I was in heaven! Which leads me to my issue. Someone in my home turned the power off at the electrical panel, which my UDM was connected to. It took almost 24 hours, but the Telus TV service started working (had picture and sound for longer than 15 seconds). Unfortunately, as I was trying to fix it, I didn't realise that the igmpproxy was working, and I think I broke it. I followed all of your steps again, but when I run igmpproxy in the foreground, I get the following error message over and over again:

MRT_DEL_MFC; Errno(2): No such file or directory

I'm stuck. I'm tempted to reset the UDM and start over again, but I don't know if that will go well. Any help or advice would be appreciated.

Sincerely
V

**Comment by peacey** [comment]
Hey @Vandypants!

That error is harmless and doesn't impact igmpproxy working properly. It's basically just saying a route it wants to delete has already been deleted or something like that. I get that error too but my TV still works. 

Are you having any issues with your TV not working?

**Comment by Vandypants** [comment]
Okay, got it. Yah, I'm having issues. Ever since the UDM lost power, the Telus PVR will not show a picture and sound after 15 seconds. What do you think the cause is?

**Comment by peacey** [comment]
It should still work if you set everything up correctly. If it's stopping after 15 seconds, it means the multicast traffic is not making it through to the TV box.

1. Make sure you're using the right brX interface in your igmpproxy.conf.
2. Make sure the PVR box is on that VLAN. 
3. Double check your firewall rules are correct, especially for letting the IGMP traffic through. 
4. Make sure igmpproxy is actually running with the right configuration when you test your TV.

**Comment by Vandypants** [comment]
Strangest thing, now the TV is working after I upgraded to firmware 1.11.4. I was on the Early Access channel. Oh well. Thank you for your help =)
