### ISSUE TITLE
Would converting from the Telus router wipe the DVR recordings?

### ISSUE THREAD

**Issue by kwilsonmg** [peacey/udm-telus#9]
I would've asked this on [the Reddit thread](https://www.reddit.com/r/Ubiquiti/comments/ploy8s/how_to_get_telus_tv_working_with_udm_and_ubiquiti/?sort=new) but saw that you were suspended @peacey . In your experience would converting the Telus boxes to use UDM result in a wipe of the PVR/DVR contents?

**Comment by peacey** [comment]
Hi @kwilsonmg,

No, it should not wipe the DVR contents if you switch your Telus box to a different WiFi network. 

Also, you can always reach me on u/peacey8. It's my new username.

**Comment by kwilsonmg** [comment]
Thank you!
